import { Inter } from '@/shared/assets/fonts';
import type { Metadata } from 'next';
import '../shared/style/_globals.scss';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={Inter.className}>{children}</body>
    </html>
  );
}
